# -*- mode: python ; coding: utf-8 -*-

import sys
sys.setrecursionlimit(5000)

block_cipher = None

a = Analysis(
    ['/workspace/xianyu-company/desktop.py'],
    pathex=['/workspace/xianyu-company'],
    binaries=[],
    datas=[
        ('/workspace/xianyu-company/config', 'config'),
        ('/workspace/xianyu-company/src/web/static', 'src/web/static')
    ],
    hiddenimports=[
        'src',
        'src.web.app',
        'src.config',
        'src.company',
        'src.models.database',
        'src.models.repo',
        'src.agents.base',
        'src.agents.ceo',
        'src.agents.purchasing',
        'src.agents.pricing',
        'src.agents.packaging',
        'src.agents.operations',
        'src.agents.review',
        'src.agents.accounting',
        'src.agents.analytics',
        'src.agents.risk_control',
        'src.tools.llm_client',
        'src.tools.dashboard',
        'src.tools.account_manager',
        'src.tools.risk_control',
        'src.tools.xianyu_messaging',
        'src.tools.xianyu_web',
        'src.tools.source_platforms',
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'websockets',
        'websockets.legacy',
        'pydantic',
        'pydantic.deprecated',
        'sqlalchemy',
        'sqlalchemy.ext.asyncio',
        'aiosqlite',
        'yaml',
        'openai',
        'httpx',
        'apscheduler',
        'apscheduler.triggers',
        'apscheduler.triggers.cron',
        'apscheduler.triggers.interval',
        'apscheduler.executors',
        'apscheduler.executors.asyncio',
        'apscheduler.jobstores',
        'apscheduler.jobstores.memory',
        'loguru',
        'pystray',
        'PIL',
        'PIL.Image',
        'PIL.ImageDraw',
        'platformdirs',
        'dotenv',
        'webview',
        'webview.platforms.gtk',
        'webview.platforms.qt',
        'webview.platforms.cocoa',
        'webview.platforms.winforms',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='闲鱼一人公司',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,  # 无控制台窗口
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
